### ISSUE TITLE
sensors.removeSensorListener not remove and stop listener event

### ISSUE THREAD

**Issue by aboire** [QuentinRoy/cordova-plugin-android-sensor-listeners#3]
I can not use "sensors.removeSensorListener", does it work on your side?

**Comment by QuentinRoy** [comment]
It does. Make sure you provided the same arguments as with `addSensorListener`.
Can you provide a bit more information?

**Comment by aboire** [comment]
I paste my example, i test on the emulator
I can see that it starts even if it returns the value to 0,0,0 but it may be due to the emulator, because when I see stop I get a looping error: 

"Error in Success callbackId: Sensors590419661 : Error: Received unexpected event from non subscribed sensor: AMBIENT_TEMPERATURE"

"Uncaught Error: Received unexpected Event from non subscribed sensor: AMBIENT_TEMPERATURE "

```    
      function listener(event) {
        if(event){
        console.log(JSON.stringify(event));
      }
      }
      Meteor.setTimeout(function(){
        sensors.addSensorListener("AMBIENT_TEMPERATURE", "NORMAL", listener, function(error) {
          if (error) console.error("Could not listen to sensor");
        });
      }, 10000);

      Meteor.setTimeout(function(){
        sensors.removeSensorListener("AMBIENT_TEMPERATURE", "NORMAL", listener, function(error) {
        if (error) console.error("Could not stop listening to sensor");
        });
      }, 15000);
```

**Comment by QuentinRoy** [comment]
Odd. I haven't tried the code on an emulator and even less with Meteor. It seems the listener does get removed on the JS side but not on the Android side. Do you get it several times or just one? It might be due to a last event being sent by Android even though JS already removed the listener.

**Comment by aboire** [comment]
The problem is that the error runs in a loop

**Comment by QuentinRoy** [comment]
Oh so you see the error multiple times? This is more annoying... I just made a patch. Do you mind installing the following branch and see if it solves your problem?
```sh
cordova plugin add https://github.com/QuentinRoy/cordova-plugin-android-sensor-listeners.git#async-remove-fix
```

**Comment by aboire** [comment]
I test now and I tell you what it is

**Comment by aboire** [comment]
I have no error but it does not stop and it loops with the event
"{" Values ": [0,0,0]," timeStamp ": 7781611065932," sensor "," AMBIENT_TEMPERATURE "," sampling ":" NORMAL "}"

**Comment by QuentinRoy** [comment]
Does the error handler gets called?  I.e. with your example above, do you get the "Could not stop listening to sensor" message and if so, can you print and tell me the error you receive in the handler?

**Comment by aboire** [comment]
Yes I have "Could not stop listening to sensor" and after that continues to send the event

**Comment by QuentinRoy** [comment]
Oh. So yeah. Something wrong happened there, this is expected that you will keep receiving the event if the listener cannot be removed. On this handler, you get an error argument:
```js
function(error) {
  if (error) console.error("Could not stop listening to sensor");
});
```
`error` is actually an object (that is `null` if there is no error, following nodejs' conventions). Can you check what that error is? You should be able to `console.log` it. E.g. `console.log(error.message||error)`.

**Comment by aboire** [comment]
Return error: "JSON error"

**Comment by QuentinRoy** [comment]
Oops! I think I found it. Can you try again (with the latest commits I pushed)?

**Comment by aboire** [comment]
Yes i rebuild and tell you

**Comment by aboire** [comment]
retrun error : "Not listener found for sensor AMBIENT_TEMPERATURE at sampling period NORMAL"

**Comment by aboire** [comment]
I have the impression that the hash is not the same

**Comment by QuentinRoy** [comment]
Yes, I think I found it. Give me 10 minutes and I'll give you a new patch. The remove listeners was indeed broken on several levels. Sorry about this.

**Comment by aboire** [comment]
It should not be the hash? listeners.put(sensorTypeName, listener);
https://github.com/QuentinRoy/cordova-plugin-android-sensor-listeners/blob/801f2156d55188df7a12f1880b0ea8fc29368b5b/src/android/Sensors.java#L180

**Comment by QuentinRoy** [comment]
OK it should be fixed now. Please check and I'll push a new version.

**Comment by QuentinRoy** [comment]
> It should not be the hash? listeners.put(sensorTypeName, listener);

Yes it should. This remains from the time the plugin did not support the sampling period setting. Fixed now.

**Comment by aboire** [comment]
Yes it works well :)

**Comment by aboire** [comment]
thanks (merci)

**Comment by QuentinRoy** [comment]
Great! Thanks for your help!
I squash merge that and publish a new release.

Passe le bonjour a ton île de ma part. I loved that place. :)
