### ISSUE TITLE
Received unexpected event from non subscribed sensor: ROTATION VECTOR

### ISSUE THREAD

**Issue by koxu1996** [QuentinRoy/cordova-plugin-android-sensor-listeners#5]
Example from README is working fine:
```
function listener(event) {
  console.log("device's rotation is " + event.values.join(','));
}

sensors.addSensorListener("ROTATION_VECTOR", "GAME", listener, function(error) {
  if (error) console.error("Could not listen to sensor");
});
```
When changed sampling from _GAME_ to _FASTEST_ then there is error:
![](https://i.imgur.com/xBnHdWI.png)

Detailed error when adding sensor listener:
```
Cannot subscribe to anything before registering a callback
```

**Comment by QuentinRoy** [comment]
Oh. This is surprising. It is possible that the first event is sent before the JS side received the confirmation of the subscription.. Unfortunately I do not have any Android devices anymore and won't be able to maintain this project before March / April. I have a an idea how I could work around this, but I'd need your help. If I create a patch, will you be able to test it out?

**Comment by QuentinRoy** [comment]
Hm. That is strange. It seems an exception is raised during the listener's registration—which might be due to something unsupported by your device—but the registration does work (since you then receive the errors).
This is most likely a problem on your device. Out of curiosity, what model & android version are you using? Did you test it and experience the same issue on a different device?

**Comment by koxu1996** [comment]
I will let you know in few days, but it looks like subscription is called before callback registration.
 
Device: Sony Xperia Z1 C6903
OS: Android 5.1.1

**Comment by QuentinRoy** [comment]
Hm. I have an idea of what might cause it. However I won't have access to an Android device before at least a few months. If I create a patch, will you be willing to test it?

**Comment by QuentinRoy** [comment]
I created a quick patch on the wait4registration branch. I won't lie: I had little time to implement it and no way to test it. But with a bit of luck it might help you.

**Comment by koxu1996** [comment]
I am glad to help you with fixing this issue. Your commit is almost perfect, but you made small mistake: wrong condition at https://github.com/QuentinRoy/cordova-plugin-android-sensor-listeners/commit/fe79cef74fbb8d76bd219755c1228312cc4f5e36#diff-7ca1d37d75b1dcdbfb1d86d43f83842eR59
After switching condition, plugin is working well :)

**Comment by QuentinRoy** [comment]
Thanks! I pushed the fix to the branch. Can you confirm that it works? Then I'll merge and publish.

**Comment by koxu1996** [comment]
Confirmed, it works.
