### ISSUE TITLE
Wrong url in README

### ISSUE THREAD

**Issue by koxu1996** [QuentinRoy/cordova-plugin-android-sensor-listeners#6]
Finally I figured out why I was having troubles with adding plugin. _Install_ section in _README.md_ contain following line:

```
cordova plugin add https://github.com/QuentinRoy/cordova-plugin-android-sensors.git
```

which should be

```
cordova plugin add https://github.com/QuentinRoy/cordova-plugin-android-sensor-listeners.git
```

**Comment by QuentinRoy** [comment]
Ooops! Good catch. I had to change the name to avoid a conflict and forgot to update.
