### ISSUE TITLE
How to use it in Ionic 2 and higher

### ISSUE THREAD

**Issue by martinsebastien** [QuentinRoy/cordova-plugin-android-sensor-listeners#8]
Hi,

Thank you very much for this plugin. I wonder why Ionic didn't already implemented some of those sensors ... 
I'd like to use the Proximity Sensor with Ionic >2 but I can't figure out how.
Can you please provide an exemple or explain how to achieve this ?
It would be great ! 
Merci beaucoup ;)

**Comment by QuentinRoy** [comment]
Unfortunately I have no idea. I never used Ionic, only Cordova. But it seems Ionic does use Cordova. What happens when you attempt to install the plugin using Cordova (`cordova plugin add https://github.com/QuentinRoy/cordova-plugin-android-sensor-listeners.git `)?

**Comment by QuentinRoy** [comment]
Apparently there is also an [`ionic cordova plugin`](https://ionicframework.com/docs/cli/cordova/plugin/) though it is supposed to do no more than adding some "friendly checks". Still, you might want to try this as well.
Let me know.

**Comment by martinsebastien** [comment]
Yes I could add the plugin without problem but I wonder how to use it inside my components. What is his name ? navigator.sensor ? cordova.sensor ? etc ...
I will run some test this evening. If I find a way to use it with Ionic I will let you know.

**Comment by QuentinRoy** [comment]
Cordova 7 injects a plugin's export (here `sensors`) directly into the global context (i.e. `window`). Hence you should be able to access `sensors` as a "global" var.
You need to wait for the `'deviceready'` event before using any plugin though.

**Comment by martinsebastien** [comment]
Ok, it's good to know! Anyway, when I try to console.log : window.sensors ((<any>window).sensors in Ionic) I get : undefined. I know that I have to use real device to debug cordova plugin (I could do that in few hours) but I think it could display something in the console anyway ? Or Do I really have to use a real device to expect something ?

**Comment by QuentinRoy** [comment]
No. I believe it should be injected even when using a simulator (again, only after `'deviceready'`).
What about `window.plugins.sensors`? Previous Cordova versions used to put plugins there.

**Comment by QuentinRoy** [comment]
I am going to close this issue as it does not seem to be related to `cordova-plugin-android-sensor-listeners` bur rather the use of cordova plugins with ionic in general.
Still, did you solve your issue?

**Comment by martinsebastien** [comment]
Yes, everything worked as expected when I tested it with a real smartphone. Thank you for your help.
